name: ordel
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
# //TODO jag har gjorde api-key för ordel dev restricted till android apps https://console.cloud.google.com/apis/credentials?referrer=search&authuser=1&hl=sv&project=ordel-dev
version: 1.1.2+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  another_flushbar: ^1.10.28
  fluro: ^2.0.3
  fluttertoast: ^8.0.8
  flip_card: ^0.6.0
  flutterfire_ui: ^0.3.1
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_remote_config: ^1.0.4
  firebase_crashlytics: ^2.4.5
  firebase_analytics: ^9.0.5
  provider: ^6.0.2
  http: ^0.13.4
  intl: ^0.17.0
  shared_preferences: ^2.0.12
  package_info_plus: ^1.3.0
  cloud_functions: ^3.2.6
  firebase_messaging: ^11.2.6
  flutter_colorpicker: ^1.0.3
  store_redirect: ^2.0.1
  native_updater: ^0.1.1
  carousel_slider: ^4.0.0
  collection: ^1.15.0
  syncfusion_flutter_charts: ^19.4.54

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  mockito: ^5.0.17
  build_runner: ^2.1.7 #flutter pub run build_runner build https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md
  flutter_lints: ^1.0.4
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
